version: "3.7"

services:
  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 7777 --reload
    ports:
      - 7777:7777
    volumes:
      - .:/code